|||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
<!-- =========================================Отправка формы============================================== -->
|||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||

<?php
//отладка ошибок
/*
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);
*/

use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;


require "PHPMailer/src/Exception.php";
require "PHPMailer/src/PHPMailer.php";
require "PHPMailer/src/SMTP.php"; //включить если smpt

$mail = new PHPMailer(true); /* Создаем объект MAIL */
$mail->CharSet = "UTF-8"; /* Задаем кодировку UTF-8 */
$mail->IsHTML(true); /* Разрешаем работу с HTML */


// Настройки SMTP включить если smpt
$mail->isSMTP();
$mail->Host = 'ssl://smtp.yandex.ru';
$mail->Port = 465;
$mail->SMTPSecure = 'tls';
$mail->SMTPAuth = true;
// $mail->SMTPDebug = 3;
$mail->Username = 'dmitryzemtsow@ya.ru'; //paste one generated by Mailtrap
$mail->Password = 'ugzbrscwkpclxaas'; //paste one generated by Mailtrap



//инпуты из формы
$name = $_POST["name"]; /* Принимаем имя пользователя с формы .. */
$email = $_POST["email"]; /* Почту */
$phone = $_POST["tel"]; /* Телефон */
$message = $_POST["text"]; /* Сообщение с формы */

$email_template = "template_mail.html"; // Считываем файл разметки
$body = file_get_contents($email_template); // Сохраняем данные в $body
$body = str_replace('%name%', $name, $body); // Заменяем строку %name% на имя
$body = str_replace('%email%', $email, $body); // строку %email% на почту
$body = str_replace('%phone%', $phone, $body); // строку %phone% на телефон
$body = str_replace('%message%', $message, $body); // строку %message% на сообщение

$mail->addAddress("1primo1@mail.ru"); /* Здесь введите Email, куда отправлять */
$mail->setFrom('dmitryzemtsow@ya.ru', 'этот сайт'); //Заменить на $email если нет smpt
$mail->Subject = "[Заявка с формы]"; /* Тема письма */
$mail->MsgHTML($body);

//если отправка успешна 
if ($mail->send()) {
    $message = "Форма успешно отправлена";
} else {
    $message = "При отправке формы произошла ошибка";
}


$response = ["message" => $message];
//возвращаем файл в js
header("Content-type: application/json");
echo json_encode($response);
